/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ChoreKind = "on_demand" | "scheduled";

export type ChoreStatus = "approved" | "pending" | "rejected" | "submitted";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type RecurrenceType = "daily" | "one_off" | "weekly";

export type RedemptionStatus = "approved" | "denied" | "fulfilled" | "requested";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "adult" | "child";

export interface ChoreAssignments {
  approved_at: Timestamp | null;
  approved_by_user_id: string | null;
  assigned_to_user_id: string;
  chore_id: string;
  created_at: Generated<Timestamp>;
  due_date: Timestamp | null;
  id: Generated<string>;
  reject_reason: string | null;
  status: Generated<ChoreStatus>;
  submitted_at: Timestamp | null;
}

export interface Chores {
  archived: Generated<boolean>;
  cooldown_minutes: Generated<number>;
  created_at: Generated<Timestamp>;
  created_by_user_id: string;
  description: string | null;
  household_id: string;
  id: Generated<string>;
  kind: Generated<ChoreKind>;
  recurrence: Generated<RecurrenceType>;
  title: string;
  token_value: number;
}

export interface Households {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
}

export interface Redemptions {
  decided_at: Timestamp | null;
  decided_by_user_id: string | null;
  decision_reason: string | null;
  id: Generated<string>;
  requested_at: Generated<Timestamp>;
  reward_id: string;
  status: Generated<RedemptionStatus>;
  tokens_spent: number;
  user_id: string;
}

export interface Rewards {
  archived: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by_user_id: string;
  description: string | null;
  household_id: string;
  id: Generated<string>;
  title: string;
  token_cost: number;
}

export interface Users {
  avatar_emoji: Generated<string>;
  created_at: Generated<Timestamp>;
  email: string | null;
  household_id: string;
  id: Generated<string>;
  name: string;
  password_hash: string | null;
  pin_hash: string | null;
  role: UserRole;
  token_balance: Generated<number>;
}

export interface DB {
  chore_assignments: ChoreAssignments;
  chores: Chores;
  households: Households;
  redemptions: Redemptions;
  rewards: Rewards;
  users: Users;
}
